# ~/.config/alacritty/alacritty.toml

[font]
size = 13.5

[font.normal]
family = "IosevkaTerm Nerd Font Mono"
style = "Regular"


[font.bold]
family = "IosevkaTerm Nerd Font Mono"
style = "Bold"

[font.italic]
family = "IosevkaTerm Nerd Font Mono"
style = "Italic"

[keyboard]
bindings = [
  # Ctrl+Tab → send custom escape sequence to tmux
  { key = "Tab", mods = "Control", chars = "\u001b[27;5;9~" },
  # Ctrl+Shift+Tab → send custom escape sequence to tmux
  { key = "Tab", mods = "Control|Shift", chars = "\u001b[27;6;9~" },
]

[window]
dimensions = { columns = 100, lines = 32 }

opacity = 1.0
dynamic_title = true

[window.padding]
x = 5
y = 2

[cursor]
style = "Block"
unfocused_hollow = true

[colors.primary]
background = "#232627"
foreground = "#fcfcfc"

[colors.normal]
black   = "#232627"
red     = "#ed1515"
green   = "#11d116"
yellow  = "#f67400"
blue    = "#1d99f3"
magenta = "#9b59b6"
cyan    = "#1abc9c"
white   = "#fcfcfc"

[colors.bright]
black   = "#7f8c8d"
red     = "#c0392b"
green   = "#1cdc9a"
yellow  = "#fdbc4b"
blue    = "#3daee9"
magenta = "#8e44ad"
cyan    = "#16a085"
white   = "#ffffff"
